
export const ON_SUCCESS_LOGIN = 'ON_SUCCESS_LOGIN'
export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN'

export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS'
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
export const CLEAR_BOOKINGS = 'CLEAR_BOOKINGS'

export const ON_REQUEST_START = 'ON_REQUEST_START'
export const ON_REQUEST_FINISH = 'ON_REQUEST_FINISH'

